version: 2.1
orbs:
  node: circleci/node@5  # Correct usage of the orb
jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:  # Install node packages using the orb
          pkg-manager: npm
      - run:
          name: Create test results directory
          command: mkdir -p ./test-results
      - run:
          name: Run tests
          command: npm run test -- --forceExit  # Force exit to avoid hanging
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Node.js and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_16.x | bash -
            apt-get install -y nodejs
      - run:
          name: deploy
          command: npx expo start && exit 0
workflows:
  build-and-test:
    jobs:
      - test-node
      - deploy:
          requires:
           - test-node